#!/bin/bash

set -evx

cd /tmp

# Compress function with pigz for faster compression
com ()
{
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1 # Compression level 1, its enough

#up(){
#        curl bashupload.com -T $1
#}

#up ccache.tar.gz

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf # Write rclone config found from env variable, so that cloud storage can be used to upload ccache
time rclone copy ccache.tar.gz aosp:ccache/ccache-ci -P # apon is my rclone config name (first line without [] of ~/.config/rclone/rclone.conf file from rclone setupped pc), ccache/c is where ccache will be saved in my cloud, use yours one
